<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>RustSharp.Conformance</AssemblyName>
    <RootNamespace>RustSharp.Conformance</RootNamespace>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RustSharp.Compiler/RustSharp.Compiler.csproj" />
    <ProjectReference Include="../../src/RustSharp.Syntax/RustSharp.Syntax.csproj" />
  </ItemGroup>
</Project>
