<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>RustSharp ECMA-335 IL and portable PDB code generator.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RustSharp.Syntax/RustSharp.Syntax.csproj" />
    <ProjectReference Include="../RustSharp.Semantics/RustSharp.Semantics.csproj" />
  </ItemGroup>
</Project>
