<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RustSharp.Syntax/RustSharp.Syntax.csproj" />
    <ProjectReference Include="../../src/RustSharp.CodeGen.IL/RustSharp.CodeGen.IL.csproj" />
    <ProjectReference Include="../../src/RustSharp.Compiler/RustSharp.Compiler.csproj" />
    <ProjectReference Include="../../src/RustSharp.Runtime/RustSharp.Runtime.csproj" />
    <ProjectReference Include="../../src/RustSharp.Semantics/RustSharp.Semantics.csproj" />
    <ProjectReference Include="../../tools/RustSharp.Conformance/RustSharp.Conformance.csproj" />
  </ItemGroup>
</Project>
